package wasi:gpio@0.2.0;

/// Digital General Purpose Input/Output (GPIO) API based on
/// `embedded_hal::digital`.
interface digital {
    use types.{error-code, pin-state};

    /// A single digital push-pull output pin.
    ///
    /// This mirrors `embedded_hal::digital::OutputPin`.
    resource output-pin {
        /// Drives the pin low.
        ///
        /// The actual electrical state of the pin may not be low, for example
        /// due to external electrical sources.
        set-low: func() -> result<_, error-code>;

        /// Drives the pin high.
        ///
        /// The actual electrical state of the pin may not be high, for example
        /// due to external electrical sources.
        set-high: func() -> result<_, error-code>;

        /// Drives the pin high or low depending on the provided state.
        set-state: func(state: pin-state) -> result<_, error-code>;
    }

    /// A push-pull output pin that can read its output state.
    ///
    /// This mirrors `embedded_hal::digital::StatefulOutputPin`. The output
    /// methods are repeated because WIT resources do not support inheritance.
    resource stateful-output-pin {
        /// Drives the pin low.
        set-low: func() -> result<_, error-code>;

        /// Drives the pin high.
        set-high: func() -> result<_, error-code>;

        /// Drives the pin high or low depending on the provided state.
        set-state: func(state: pin-state) -> result<_, error-code>;

        /// Returns whether the pin is in drive-high mode.
        ///
        /// This does not read the electrical state of the pin.
        is-set-high: func() -> result<bool, error-code>;

        /// Returns whether the pin is in drive-low mode.
        ///
        /// This does not read the electrical state of the pin.
        is-set-low: func() -> result<bool, error-code>;

        /// Toggles the pin output.
        toggle: func() -> result<_, error-code>;
    }

    /// A single digital input pin.
    ///
    /// This mirrors `embedded_hal::digital::InputPin`.
    resource input-pin {
        /// Returns whether the input pin is high.
        is-high: func() -> result<bool, error-code>;

        /// Returns whether the input pin is low.
        is-low: func() -> result<bool, error-code>;
    }

    open-output: func(name: string) -> result<output-pin, error-code>;

    open-stateful-output: func(name: string) -> result<stateful-output-pin, error-code>;

    open-input: func(name: string) -> result<input-pin, error-code>;
}
